//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCustomer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class tbl_Booking
    {
        [Required(ErrorMessage = "Required Theater ID")]
        public int Theater_Id { get; set; }

        [Required(ErrorMessage = "Required which Movie")]
        public string Movie { get; set; }

        [Required(ErrorMessage = "Required Which Show")]
        public string Show { get; set; }

        [Required(ErrorMessage = "Required Type of Ticket")]
        public string Ticket_Type { get; set; }

        [Required(ErrorMessage = "Required Number of Persons")]
        public Nullable<int> Persons { get; set; }
        public int _cost;
        public Nullable<int> Cost {
            get
            {
                return Persons * _cost;
            }
            set
            {
                if (Ticket_Type == "Diamond")
                    _cost = 200;
                else if (Ticket_Type == "Platinum")
                    _cost = 150;
                else
                    _cost = 100;
            }
        }

        [Required(ErrorMessage = "Required Payment Method")]
        public string Payment__Type { get; set; }
    }
}
