//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCustomer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movie
    {
        public int Movie_Id { get; set; }
        public string Movie_Name { get; set; }
        public string Movie_Genre { get; set; }
        public string Movie_Director { get; set; }
        public string Movie_Length { get; set; }
        public string Languages { get; set; }
        public string Release_Date { get; set; }
    }
}
