//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCustomer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Customer
    {
        [Required(ErrorMessage = "Id should be of Minimum 6 Digits")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Required Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public string Date_of_Birth { get; set; }

        public string Tickets { get; set; }

        [Required(ErrorMessage = "Required MobileNo")]
        [MinLength(6, ErrorMessage = "Mobile no Is needed")]
        public string Contact_No { get; set; }
    }
}
